name: ent_cldm
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.4
  - cudatoolkit=10.2.89
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1s
  - pillow=9.3.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - annexremote==1.6.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==22.2.0
    - babel==2.12.1
    - bitarray==2.6.2
    - boto==2.49.0
    - chardet==5.1.0
    - clldutils==3.19.0
    - colorama==0.4.6
    - colorlog==6.7.0
    - csvw==3.1.3
    - cython==0.29.33
    - datalad==0.18.2
    - datasets==2.9.0
    - dill==0.3.6
    - distro==1.8.0
    - dlinfo==1.2.1
    - fairseq==0.12.2
    - fasteners==0.18
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - h5py==3.8.0
    - huggingface-hub==0.12.0
    - humanize==4.6.0
    - hydra-core==1.0.7
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - iso8601==1.1.0
    - isodate==0.6.1
    - jaraco-classes==3.2.3
    - jeepney==0.8.0
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kenlm==0.1
    - keyring==23.13.1
    - keyrings-alt==4.2.0
    - language-tags==1.2.0
    - looseversion==1.1.2
    - lxml==4.9.2
    - markdown==3.4.1
    - markupsafe==2.1.2
    - more-itertools==9.1.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.14
    - npy-append-array==0.9.15
    - omegaconf==2.0.6
    - packaging==23.0
    - pandas==1.5.3
    - patool==1.12
    - phonemizer==3.2.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.1
    - portalocker==2.7.0
    - protobuf==3.20.1
    - pyarrow==11.0.0
    - pylangacq==0.18.0
    - pylatexenc==2.10
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-gitlab==3.13.0
    - pytz==2022.7.1
    - pyyaml==6.0
    - rdflib==6.2.0
    - regex==2022.10.31
    - requests-toolbelt==0.10.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - sacrebleu==2.3.1
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - secretstorage==3.3.3
    - segments==2.2.1
    - soundfile==0.11.0
    - tabulate==0.9.0
    - tensorboardx==2.5.1
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.26.0
    - uritemplate==4.1.1
    - wcwidth==0.2.6
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.12.0
