checkpoint: openai/whisper-base.en # the whisper model to use as encoder (a huggingface checkpoint)
utterances: data/cougar/model_inputs/cougar.sorted # path to file containing the utterances (this file has '.sorted' as extension)
h5_data: data/cougar/model_inputs/cougar.hdf5 # path to the h5py data (this file has '.h5py' as extension)
targets: data/cougar/model_inputs/cougar.entropies # path to the file storing the targets for training (this file has '.entropies' as extension)
batch_size: 32
model_checkpoint: checkpoints/Thomas_30h_Librispeech360_en.pt # The name of the checkpoint to be used
output_folder: results # Where the results will be saved